# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1e\n\x10UserParamRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"T\n\x0bUserRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\"\xb5\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x05 \x01(\t\x12\x14\n\x0c\x63reated_date\x18\x06 \x01(\t\x12\x12\n\ncreated_by\x18\x07 \x01(\t\x12\x14\n\x0cupdated_date\x18\x08 \x01(\t\x12\x12\n\nupdated_by\x18\t \x01(\t\"=\n\x0fUserListRequest\x12\x0e\n\x06search\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\"e\n\x10UserListResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.user.UserResponse\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\r\n\x05total\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x32\xa0\x02\n\x04User\x12\x39\n\x08GetUsers\x12\x15.user.UserListRequest\x1a\x16.user.UserListResponse\x12\x35\n\x07GetUser\x12\x16.user.UserParamRequest\x1a\x12.user.UserResponse\x12\x33\n\nCreateUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12\x33\n\nUpdateUser\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12<\n\nDeleteUser\x12\x16.user.UserParamRequest\x1a\x16.user.UserParamRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERPARAMREQUEST']._serialized_start=20
  _globals['_USERPARAMREQUEST']._serialized_end=50
  _globals['_USERREQUEST']._serialized_start=52
  _globals['_USERREQUEST']._serialized_end=136
  _globals['_USERRESPONSE']._serialized_start=139
  _globals['_USERRESPONSE']._serialized_end=320
  _globals['_USERLISTREQUEST']._serialized_start=322
  _globals['_USERLISTREQUEST']._serialized_end=383
  _globals['_USERLISTRESPONSE']._serialized_start=385
  _globals['_USERLISTRESPONSE']._serialized_end=486
  _globals['_USER']._serialized_start=489
  _globals['_USER']._serialized_end=777
# @@protoc_insertion_point(module_scope)
